#!/bin/bash

echo "🔥 Firebase Configuration Setup"
echo "==============================="
echo ""
echo "📋 Step 1: Get Firebase Config"
echo "1. Go to: https://console.firebase.google.com/project/spoileralert-firebase/settings/general"
echo "2. Scroll to 'Your apps' → Add app → Web"
echo "3. App nickname: 'SpoilerAlert Web'"
echo "4. Copy the Firebase config object"
echo ""
echo "📝 Step 2: Create .env file"
echo "Create a .env file in your project root with:"
echo ""
echo "FIREBASE_API_KEY=your-api-key"
echo "FIREBASE_AUTH_DOMAIN=spoileralert-firebase.firebaseapp.com"
echo "FIREBASE_PROJECT_ID=spoileralert-firebase"
echo "FIREBASE_STORAGE_BUCKET=spoileralert-firebase.appspot.com"
echo "FIREBASE_MESSAGING_SENDER_ID=65007432609"
echo "FIREBASE_APP_ID=your-app-id"
echo ""
echo "🚀 Step 3: Test Firebase Integration"
echo "1. Restart your dev server: npm run dev"
echo "2. Visit http://localhost:9000/"
echo "3. Look for the Firebase Integration Test section"
echo ""
echo "✅ Ready to configure Firebase!"

